<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\FirestoreHelper.cs" />
    <Compile Remove="Data\IAuthentication.cs" />
    <Compile Remove="Data\RestService.cs" />
    <Compile Remove="Data\TokenDatabaseController.cs" />
    <Compile Remove="Maps\PartyPin.cs" />
    <Compile Remove="Models\Constants.cs" />
    <Compile Remove="Models\Friend.cs" />
    <Compile Remove="Models\Person.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseDatabase.net" Version="4.0.4" />
    <PackageReference Include="FirebaseStorage.net" Version="1.0.3" />
    <PackageReference Include="MagicGradients" Version="1.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="RestSharp" Version="106.11.4" />
    <PackageReference Include="sqlite" Version="3.13.0" />
    <PackageReference Include="sqlite-net-pcl" Version="1.7.335" />
    <PackageReference Include="Xam.Plugin.Media" Version="5.0.1" />
    <PackageReference Include="Xamarin.Auth" Version="1.7.0" />
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.2" />
    <PackageReference Include="Xamarin.Forms" Version="4.7.0.1080" />
    <PackageReference Include="Xamarin.Forms.GoogleMaps" Version="3.3.0" />
    <PackageReference Include="ZXing.Net.Mobile" Version="2.4.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\FriendsPage.xaml.cs">
      <DependentUpon>FriendsPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\HomePage.xaml.cs">
      <DependentUpon>HomePage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\PartyHostPage.xaml.cs">
      <DependentUpon>PartyHostPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SettingsPage.xaml.cs">
      <DependentUpon>SettingsPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SignUpPage.xaml.cs">
      <DependentUpon>SignUpPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MasterTabbedPage.xaml.cs">
      <DependentUpon>MasterTabbedPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Views\AddFriendPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\FeedPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\FriendsPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\HomePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\LogInPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\NewPostPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PartyHostPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PartyPostPreviewPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PostViewPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ProfilePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\SettingsPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="SettingsMaster.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\SignUpPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\MasterTabbedPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>